name: fpm

on: [push, pull_request]
env:
  STDLIB_GITHUB: "fortran-lang/stdlib"
  GCC_V: "10"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dp-stdlib ğŸ‘
      uses: actions/checkout@v2.3.1
    
    - name: Checkout fortran-lang/stdlib ğŸ›ï¸
      uses: actions/checkout@v2.3.1
      with:
        repository: ${{ env.STDLIB_GITHUB }}
        path: "stdlib"

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Generate stdlib-fpm package ğŸ”§
      run: |
        ls
        cp src/common.fypp stdlib/src/common.fypp
        cd stdlib && bash ./ci/fpm-deployment.sh
        
    - name: Install GFortran
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ env.GCC_V }} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ env.GCC_V }} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ env.GCC_V }}
        
    - name: Install fpm latest release
      uses: fortran-lang/setup-fpm@v3
      with:
        fpm-version: 'v0.4.0'

    # - name: Run fpm test âš™
    #   run: |
    #     cp -r stdlib-fpm stdlib-fpm-test
    #     cd stdlib-fpm-test
    #     fpm test
    #     fpm test --profile release
        
    # Update and deploy the f90 files generated by github-ci to the `main` branch.
    - name: Copy
      run:
        rm -rf stdlib/stdlib-fpm/test/ && rm stdlib/stdlib-fpm/array3.dat &&
        cp -r stdlib/stdlib-fpm/ stdlib-fpm/ &&
        cp README.md stdlib-fpm/
    
    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: github.event_name != 'pull_request'
      with:
        BRANCH: main
        FOLDER: stdlib-fpm